Add Dockerfile for hasura + push it to Docker Hub via Github Actions
HSLdevcom/jore4-sql-schema-experiment pull request #11
Opened 2021-03-18 08:48 UTC by tk-vincit

2021-03-18 09:09 UTC, lassemaatta reviewed
+1 from me, but someone else might also take a look.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-:-MW3a28EDD0TD_ByzG0d:bdq2avu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haphut and @pallost)



<!-- Sent from Reviewable.io -->

2021-03-18 14:57 UTC, haphut requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11)* status: all files reviewed, 16 unresolved discussions (waiting on @pallost and @tk-vincit)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW45Fz39e9Zwq228odl:-MW45Fz39e9Zwq228odm:b-y31o1s) (no related file):*
Excellent stuff!

I would separate the Dockerfile creation into one PR and the initial CI into another. At least I'd separate them into different commits.

---
*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4i05lERCk15D4w7nr:-MW4i05lERCk15D4w7ns:b5ji7r3) (no related file):*
The Dockerfile approach of wrapping Hasura hard codes the metadata and migrations directories. We should either:
1. document in `README.md` that `HASURA_GRAPHQL_MIGRATIONS_DIR` and `HASURA_GRAPHQL_METADATA_DIR` should either always be set to their defaults `/hasura-migrations` and `/hasura-metadata` or never be set, or
2. block the effects of the environment variables and possible server CLI arguments in the Dockerfile.

The GraphQL API or the migrations will break, if any other values are set. Since we are removing that configurability, we are responsible for reducing the user options.

---
___
*[Dockerfile, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW45obA8R5tG21TyMZ7:-MW45obA8R5tG21TyMZ8:b-w5fsa9) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L2)):*
> ```Dockerfile
> FROM hasura/graphql-engine:v1.3.3.cli-migrations-v2
> EXPOSE 8080
> ```

This is inherited from the base image and unnecessary.
___
*[Dockerfile, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4djnw-Ubr5NkuweLR:-MW4djnw-Ubr5NkuweLS:b-gyq6qi) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L3)):*
> ```Dockerfile
> FROM hasura/graphql-engine:v1.3.3.cli-migrations-v2
> EXPOSE 8080
> WORKDIR /app
> ```

This sets the directory in the Dockerfile context and is unnecessary here.
___
*[Dockerfile, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4dtwiC4AMDcs1O5QK:-MW4dtwiC4AMDcs1O5QL:b-khbqo) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L4)):*
> ```Dockerfile
> EXPOSE 8080
> WORKDIR /app
> ENV HASURA_GRAPHQL_ENABLE_CONSOLE="false"
> ```

I would put this one into kube yaml.
___
*[Dockerfile, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4e3NV5cudSrMTj5WW:-MW4e3NV5cudSrMTj5WX:b-khbqo) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L5)):*
> ```Dockerfile
> WORKDIR /app
> ENV HASURA_GRAPHQL_ENABLE_CONSOLE="false"
> ENV HASURA_GRAPHQL_ENABLE_TELEMETRY="false"
> ```

I would put this one into kube yaml.
___
*[Dockerfile, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4dppnBOXJAWFV0uiF:-MW4dppnBOXJAWFV0uiG:b-8pcp6a) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L6)):*
> ```Dockerfile
> ENV HASURA_GRAPHQL_ENABLE_CONSOLE="false"
> ENV HASURA_GRAPHQL_ENABLE_TELEMETRY="false"
> ENV HASURA_GRAPHQL_UNAUTHORIZED_ROLE="anonymous"
> ```

This is a great point! The metadata currently expects `anonymous` so this should be set here.

Again, setting this to a conflicting value should be prevented either programmatically or by documentation.
___
*[Dockerfile, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4jyHS0iy5ZUw2-6v6:-MW4jyHS0iy5ZUw2-6v7:b94fz8r) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L7)):*
> ```Dockerfile
> ENV HASURA_GRAPHQL_ENABLE_TELEMETRY="false"
> ENV HASURA_GRAPHQL_UNAUTHORIZED_ROLE="anonymous"
> COPY ./hasura/migrations ./hasura/migrations
> ```

Does not work. Should be `COPY ./hasura/migrations /hasura-migrations`.
___
*[Dockerfile, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4kA2V94Ca5Lf9Ra9P:-MW4kA2V94Ca5Lf9Ra9Q:b-jauic5) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L8)):*
> ```Dockerfile
> ENV HASURA_GRAPHQL_UNAUTHORIZED_ROLE="anonymous"
> COPY ./hasura/migrations ./hasura/migrations
> COPY ./hasura/metadata ./hasura/metadata
> ```

Does not work. Should be `COPY ./hasura/metadata /hasura-metadata`.
___
*[.github/workflows/ci.yml, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4pOmH078LQydaDZeV:-MW4pOmH078LQydaDZeW:b-wa2pqr) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L13)):*
> ```YAML
>   push_to_registry:
>     name: Build & Push docker image to Docker Hub
>     runs-on: ubuntu-latest
> ```

I'm used to pinning this in all workflows, e.g. `ubuntu-20.04`.
___
*[.github/workflows/ci.yml, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4m3Dw2Nj8A1jadPHk:-MW4m3Dw2Nj8A1jadPHl:b17av4c) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L27)):*
> ```YAML
>           echo "COMMIT_ID=$BRANCH_NAME-$GITHUB_SHA" >> $GITHUB_ENV
> 
>       - name: Pull previous image to support caching
> ```

Nice trick!
___
*[.github/workflows/ci.yml, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4kzWk5E8I4Nxu38ud:-MW4kzWk5E8I4Nxu38ue:b-ed9lre) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L28)):*
> ```YAML
> 
>       - name: Pull previous image to support caching
>         run: docker pull $IMAGE_NAME:latest || echo "Previous image not found"
> ```

Maybe echo to stderr?
___
*[.github/workflows/ci.yml, line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4l9-A3IODkv4d2FEY:-MW4l9-A3IODkv4d2FEZ:bdbilua) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L31)):*
> ```YAML
> 
>       - name: build docker image for distribution
>         run: docker build --cache-from=$IMAGE_NAME:latest -t $IMAGE_NAME:latest .
> ```

Is `--cache-from` necessary? At least in local development Docker seems to know which layers it has available. @pallost , do you know?
___
*[.github/workflows/ci.yml, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4lSkLEQYn9PgW8C2T:-MW4lSkLEQYn9PgW8C2U:b-u68e2f) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L34)):*
> ```YAML
> 
>       - name: tag docker image as '<branch_name>-<git_commit_sha>'
>         run: docker tag $IMAGE_NAME:latest $IMAGE_NAME:$COMMIT_ID
> ```

I would also like to see something like `git-$COMMIT_ID`. That way it is uniform over all branches. I'm not sure where I would use it, though.
___
*[.github/workflows/ci.yml, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4lg100W-IB3lwOuRF:-MW4lg100W-IB3lwOuRG:b-94yxzp) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L36)):*
> ```YAML
>         run: docker tag $IMAGE_NAME:latest $IMAGE_NAME:$COMMIT_ID
> 
>       - name: Login to DockerHub
> ```

typo: "Docker Hub" (like above and below)
___
*[.github/workflows/ci.yml, line 37 at r1](https://reviewable.io/reviews/hsldevcom/ [...]

2021-03-19 12:52 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11)* status: all files reviewed, 16 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW45Fz39e9Zwq228odl:-MW9X7g05BaONWKi82-z:b-2ar1xv) (no related file):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Excellent stuff!

I would separate the Dockerfile creation into one PR and the initial CI into another. At least I'd separate them into different commits.
</blockquote></details>

As you wish, I'll split those into different commits for now.
Creating separate pull requests is a bit clumsy with our current workflow and since review commits are already here, I think that it makes more sense to keep both there.

---
___
*[Dockerfile, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW45obA8R5tG21TyMZ7:-MW9ToSF-Vw8LBLR_ask:b-guets1) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L2)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

This is inherited from the base image and unnecessary.
</blockquote></details>

So, do we want to remove this? I don't know what would be conventional way in this case, but one would argue that explicitly defining exposed port increases readability and might make developer's live easier.
___
*[Dockerfile, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4djnw-Ubr5NkuweLR:-MW9UR8WCFGQbSSD1-4J:b7au5pd) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L3)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

This sets the directory in the Dockerfile context and is unnecessary here.
</blockquote></details>

OK, I'll remove this.
___
*[Dockerfile, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4dtwiC4AMDcs1O5QK:-MW9UTsd2coadwtW4n1P:b-9qln2d) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L4)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I would put this one into kube yaml.
</blockquote></details>

OK. I wasn't sure if we want to have these here or set these outside.
___
*[Dockerfile, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4e3NV5cudSrMTj5WW:-MW9UZRQ5_ru6w0ZI2sz:b-wfsjov) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L5)):*
> OK. I wasn't sure if we want to have these here or set these outside.
___
*[Dockerfile, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4dppnBOXJAWFV0uiF:-MW9Udin8h2gfK7rjF8q:b-dadkim) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L6)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

This is a great point! The metadata currently expects `anonymous` so this should be set here.

Again, setting this to a conflicting value should be prevented either programmatically or by documentation.
</blockquote></details>

Where do we want to document this? Would just adding comment here be sufficient?
Blocking conflicting values might be a bit tricky, do you have ideas how it could be done?
___
*[Dockerfile, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4jyHS0iy5ZUw2-6v6:-MW9UxhaEnSRLHCMCvY_:b-24q83h) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L7)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Does not work. Should be `COPY ./hasura/migrations /hasura-migrations`.
</blockquote></details>

Are you sure? E.g. `frontend/Dockerfile` in our graphql-playgroud repo has statement like `COPY --chown=node:node ./src ./src` and since docker image based on that Dockerfile is succesfully deployed I'm pretty sure that it works.
___
*[.github/workflows/ci.yml, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4pOmH078LQydaDZeV:-MW9Wx1_9DGS3gs43dcq:bnl11ok) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L13)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I'm used to pinning this in all workflows, e.g. `ubuntu-20.04`.
</blockquote></details>

I don't know which is best practice, but OK, let's lock this.
___
*[.github/workflows/ci.yml, line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4l9-A3IODkv4d2FEY:-MW9VM5K91UjTVd-TN2f:b1bmdza) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L31)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Is `--cache-from` necessary? At least in local development Docker seems to know which layers it has available. @pallost , do you know?
</blockquote></details>

I also noticed that `--cache-from` is not locally needed. Because of that I checked if this is needed in CI, and seems like it is.
See e.g. https://github.com/HSLdevcom/jore4-graphql-playground/runs/2148200676?check_suite_focus=true (without --cache-from, does not utilize cache) and https://github.com/HSLdevcom/jore4-graphql-playground/runs/2148177913?check_suite_focus=true (with --cache-from and utilizes cache :) )
___
*[.github/workflows/ci.yml, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4lSkLEQYn9PgW8C2T:-MW9Wa8p0Jnayp7ga_Ku:b89qldh) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L34)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I would also like to see something like `git-$COMMIT_ID`. That way it is uniform over all branches. I'm not sure where I would use it, though.
</blockquote></details>

Well. Maybe we'll add that when we have need for it. :) Or then refactor branch name ouf of current tags. 
___
*[.github/workflows/ci.yml, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4lg100W-IB3lwOuRF:-MW9VpW_5t7m2YRP9I4d:b8df0wi) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L36)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

typo: "Docker Hub" (like above and below)
</blockquote></details>

Will fix this
___
*[.github/workflows/ci.yml, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4mlgTBFQML9FAJzX8:-MW9W-C96chOVWHYfD_H:blw9im8) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L37)):*
> from
Fair point. Since we use Docker Hub, I decided that we can trus also Docker's organization. But maybe we can add backlog item about this and then make also official decision.


<!-- Sent from Reviewable.io -->

2021-03-19 13:01 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11)* status: all files reviewed, 16 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)

___
*[.github/workflows/ci.yml, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4kzWk5E8I4Nxu38ud:-MW9YwQY4VnHAJiXEBDp:b7qrb1j) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L28)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Maybe echo to stderr?
</blockquote></details>

Somehow like this? `>&2 echo "Previous image not found"` Or what is the recommended way for this?
Can change this if you want, but don't know if it adds much value for anyone.

Please note:
- We have already verified that current solution works: https://github.com/HSLdevcom/jore4-sql-schema-experiment/runs/2137849162?check_suite_focus=true
- We (should) end up into echo statement only one, when :latest image is not yet pushed to Docker Hub.


<!-- Sent from Reviewable.io -->

2021-03-19 13:03 UTC, tk-vincit reviewed
Thanks!

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-:-MW9_DpJ8OLRx9bsgFKC:b-ucfknh)* status: all files reviewed, 16 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)

___
*[Dockerfile, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4kA2V94Ca5Lf9Ra9P:-MW9ZzcH68Ilg4SZWJ71:bxjzn45) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L8)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Does not work. Should be `COPY ./hasura/metadata /hasura-metadata`.
</blockquote></details>

Let's continue discussion on the comment above.
___
*[.github/workflows/ci.yml, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4m3Dw2Nj8A1jadPHk:-MW9_35W-p96LFvTrNpN:b580dhm) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L27)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Nice trick!
</blockquote></details>

Thanks and kudos for @pallost about this idea :) 


<!-- Sent from Reviewable.io -->

2021-03-22 09:46 UTC, haphut requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @haphut, @lassemaatta, @pallost, and @tk-vincit)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4i05lERCk15D4w7nr:-MWOFfhT-Z5flLsvOdHD:b8j794q) (no related file):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

The Dockerfile approach of wrapping Hasura hard codes the metadata and migrations directories. We should either:
1. document in `README.md` that `HASURA_GRAPHQL_MIGRATIONS_DIR` and `HASURA_GRAPHQL_METADATA_DIR` should either always be set to their defaults `/hasura-migrations` and `/hasura-metadata` or never be set, or
2. block the effects of the environment variables and possible server CLI arguments in the Dockerfile.

The GraphQL API or the migrations will break, if any other values are set. Since we are removing that configurability, we are responsible for reducing the user options.
</blockquote></details>

Perhaps a cleaner approach altogether would be to enable us to directly use the official images in Kubernetes. That would require some volume capability in our clusters which probably takes more work than creating these "config Dockerfiles".

---
___
*[Dockerfile, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW45obA8R5tG21TyMZ7:-MWO5j4gAtm5SrhRnNri:bpw8cj8) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L2)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

So, do we want to remove this? I don't know what would be conventional way in this case, but one would argue that explicitly defining exposed port increases readability and might make developer's live easier.
</blockquote></details>

I was mistaken. 8080 is only the default value for `HASURA_GRAPHQL_SERVER_PORT` and thus the original Dockerfile does not explicitly specify it. The server binary checks the value and acts accordingly.

We should not hard code 8080, either.

(References:

https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/reference.html#command-flags 

https://github.com/hasura/graphql-engine/blob/f2724c97b4d7c50261a89698c1688e6ba613d8f6/server/packaging/build/Dockerfile

https://github.com/hasura/graphql-engine/blob/2099208e4b12fe2f35c3def8c1d28f8a9fae6de5/scripts/cli-migrations/v2/Dockerfile

)
___
*[Dockerfile, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4dppnBOXJAWFV0uiF:-MWO5DR8-GsjjVaaTOTD:b-5s9ahm) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L6)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Where do we want to document this? Would just adding comment here be sufficient?
Blocking conflicting values might be a bit tricky, do you have ideas how it could be done?
</blockquote></details>

I tried `CMD ["FOO=bar", "sh"]` with a toy image and that did not help to override `FOO`. We'd also need to look after the CLI options. Maybe modifying `ENTRYPOINT` would help. Maybe we would need our own wrapper script.

As that sounds complex and brittle, I'm okay with just documenting which variables to be careful with when deploying.
I would document those in README.md under "Use of the Docker image". Right now it would conflict with PR #12 which is fine. I can fix that one.
___
*[Dockerfile, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4jyHS0iy5ZUw2-6v6:-MWO4who-Q1JGA5I5il8:b-8gjynl) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L7)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Are you sure? E.g. `frontend/Dockerfile` in our graphql-playgroud repo has statement like `COPY --chown=node:node ./src ./src` and since docker image based on that Dockerfile is succesfully deployed I'm pretty sure that it works.
</blockquote></details>

I mean the target directory should have `-` instead of `/` in it as that is where Hasura will look with default settings. Just a typo. Same below.
___
*[.github/workflows/ci.yml, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4kzWk5E8I4Nxu38ud:-MWOCLpC9qGZpKphSuGb:b-4beb1l) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L28)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Somehow like this? `>&2 echo "Previous image not found"` Or what is the recommended way for this?
Can change this if you want, but don't know if it adds much value for anyone.

Please note:
- We have already verified that current solution works: https://github.com/HSLdevcom/jore4-sql-schema-experiment/runs/2137849162?check_suite_focus=true
- We (should) end up into echo statement only one, when :latest image is not yet pushed to Docker Hub.
</blockquote></details>

Yes, like that. It's fine if you don't wish to change this.
___
*[.github/workflows/ci.yml, line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4l9-A3IODkv4d2FEY:-MWOIw254PcSh1MmVG11:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L31)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I also noticed that `--cache-from` is not locally needed. Because of that I checked if this is needed in CI, and seems like it is.
See e.g. https://github.com/HSLdevcom/jore4-graphql-playground/runs/2148200676?check_suite_focus=true (without --cache-from, does not utilize cache) and https://github.com/HSLdevcom/jore4-graphql-playground/runs/2148177913?check_suite_focus=true (with --cache-from and utilizes cache :) )
</blockquote></details>

Thanks!
___
*[.github/workflows/ci.yml, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4mlgTBFQML9FAJzX8:-MWO8hvn-EBPF_b8E9gs:b-9p32ek) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L37)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

> from
Fair point. Since we use Docker Hub, I decided that we can trus also Docker's organization. But maybe we can add backlog item about this and then make also official decision.
</blockquote></details>

Good point regarding Docker Hub, I agree with you. This should not be changed. We can continue discussion regarding other actions when it becomes relevant.


<!-- Sent from Reviewable.io -->

2021-03-22 09:47 UTC, haphut reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-03-22 10:27 UTC, haphut reviewed
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11)* status: all files reviewed, 5 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-03-22 10:54 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11)* status: all files reviewed, 4 unresolved discussions (waiting on @haphut and @pallost)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4i05lERCk15D4w7nr:-MWOZLJvEc5umzUMM9rs:bh7nmgl) (no related file):*
> /hasura-migrations
Documented those in README for now. Is that OK?

---
___
*[Dockerfile, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW45obA8R5tG21TyMZ7:-MWOStXhEddPWowIavMS:bdzej59) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L2)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I was mistaken. 8080 is only the default value for `HASURA_GRAPHQL_SERVER_PORT` and thus the original Dockerfile does not explicitly specify it. The server binary checks the value and acts accordingly.

We should not hard code 8080, either.

(References:

https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/reference.html#command-flags 

https://github.com/hasura/graphql-engine/blob/f2724c97b4d7c50261a89698c1688e6ba613d8f6/server/packaging/build/Dockerfile

https://github.com/hasura/graphql-engine/blob/2099208e4b12fe2f35c3def8c1d28f8a9fae6de5/scripts/cli-migrations/v2/Dockerfile

)
</blockquote></details>

OK, I'll remove this
___
*[Dockerfile, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4dppnBOXJAWFV0uiF:-MWOXtQtAQwyjWLO1PhT:b-bwwvzl) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L6)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I tried `CMD ["FOO=bar", "sh"]` with a toy image and that did not help to override `FOO`. We'd also need to look after the CLI options. Maybe modifying `ENTRYPOINT` would help. Maybe we would need our own wrapper script.

As that sounds complex and brittle, I'm okay with just documenting which variables to be careful with when deploying.
I would document those in README.md under "Use of the Docker image". Right now it would conflict with PR #12 which is fine. I can fix that one.
</blockquote></details>

OK, added mention about this to README
___
*[Dockerfile, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4jyHS0iy5ZUw2-6v6:-MWOWAThBNUeIzzDnUoX:b-tn84li) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L7)):*
> Use of the Docker image
Ah. Sorry, I was thinking that your comment was about `.` before the second parameter (`./` vs `/`) and I completely missed the hyphen! 
Fixed.
___
*[.github/workflows/ci.yml, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4kzWk5E8I4Nxu38ud:-MWOX9iFEpJJLWvP3Tv3:bqbzn94) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L28)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Yes, like that. It's fine if you don't wish to change this.
</blockquote></details>

Well...
seems like `>&2` syntax works, but the output itself looks exactly the same as logging to standard output at least in web ui: https://github.com/HSLdevcom/jore4-sql-schema-experiment/runs/2165242578?check_suite_focus=true

But OK, I'll change this.
___
*[.github/workflows/ci.yml, line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4l9-A3IODkv4d2FEY:-MWOXX2d7jz5YqNUJM79:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L31)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Done
___
*[.github/workflows/ci.yml, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4mlgTBFQML9FAJzX8:-MWOXUJ360XFfvFzWaDX:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/.github/workflows/ci.yml#L37)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Good point regarding Docker Hub, I agree with you. This should not be changed. We can continue discussion regarding other actions when it becomes relevant.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-03-22 15:44 UTC, haphut reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4i05lERCk15D4w7nr:-MWPasQC97uO1mX4IXs7:b-5fqpeq) (no related file):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

> /hasura-migrations
Documented those in README for now. Is that OK?
</blockquote></details>

Great! Thanks.

---
___
*[Dockerfile, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4jyHS0iy5ZUw2-6v6:-MWPaP1xDYQiMndheTMw:b-71nua6) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L7)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

> Use of the Docker image
Ah. Sorry, I was thinking that your comment was about `.` before the second parameter (`./` vs `/`) and I completely missed the hyphen! 
Fixed.
</blockquote></details>

Thanks! I should not have changed that detail.
___
*[README.md, line 7 at r4](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MWPaeCQ4-IBF6Sn28GR:-MWPaeCQ4-IBF6Sn28GS:b-z5gnbo) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/5f4bf12b0738627dbc441ca129057fb57b8a67fd/README.md#L7)):*
> ```Markdown
> ## Use of the Docker image
> 
> Docker image expects following env variables, which are **set by default**.
> ```

s/following/the following/
___
*[README.md, line 15 at r4](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MWP_on_6JqcrZNkabtv:-MWP_on_6JqcrZNkabtw:b-9h5nbe) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/5f4bf12b0738627dbc441ca129057fb57b8a67fd/README.md#L15)):*
> ```Markdown
> | HASURA_GRAPHQL_METADATA_DIR | /hasura-metadata |
> 
> **Please don't change those, so either don't define those at all or then set those to the same values as documened above.**
> ```

s/then//
s/documened/documented/


<!-- Sent from Reviewable.io -->

2021-03-22 15:45 UTC, haphut approved these changes
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11)* status: all files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-03-22 16:32 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pallost)

___
*[Dockerfile, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MW4jyHS0iy5ZUw2-6v6:-MWPlQEZ2oyVszQwDTlO:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6907564ea414c2ce84b2e7efd7232f33db8a74f9/Dockerfile#L7)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Thanks! I should not have changed that detail.
</blockquote></details>

Done
___
*[README.md, line 7 at r4](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MWPaeCQ4-IBF6Sn28GR:-MWPlf0rCrR9UIl1jjmO:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/5f4bf12b0738627dbc441ca129057fb57b8a67fd/README.md#L7)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

s/following/the following/
</blockquote></details>

Done
___
*[README.md, line 15 at r4](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/11#-MWP_on_6JqcrZNkabtv:-MWPlnsr0MvI_ixphTEJ:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/5f4bf12b0738627dbc441ca129057fb57b8a67fd/README.md#L15)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

s/then//
s/documened/documented/
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-03-22 16:35 UTC, merged